### ISSUE TITLE
Unable to hang G36 on gun wall

### ISSUE THREAD

**Issue by Frednoeyes** [CiarenceW/G36C_plugin#1]
For whatever reason the new G36 has no prompt to hang it on the wall in the Compound. There is a prompt to put it on the cleaning spot, but that just causes the gun to be dropped on the floor, not actually placed on the table.

**Comment by CiarenceW** [comment]
yeah I forgot to give it a pegboard hanger, oops.
Will add one next update, or when I can be arsed

**Comment by Frednoeyes** [comment]
All good, you think you could model the full size G36 with the weird
Hensoldt dual optic? Might be fun, considering the red dot had like a 10
degree FOV.

**Comment by CiarenceW** [comment]
I think it's kinda above my modeling skills, I guess I could take it from the World of Guns model and add more polygons but ehhhhhhhhhhhhhhhhh I'm not that interested in making another full auto assault rifle for the time being :(
Oh also I just updated the ThunderStore version to feature the Pegboard Hanger

**Comment by Frednoeyes** [comment]
Fair enough, great job so far! You're about the only guy making mods for
Receiver II, so I'll take what I can get.

**Comment by CiarenceW** [comment]
Szikaka's going to release a new gun soon-ish
